name: release
on:
  release:
    types: [published]
env:
  CI_XCODE_VER: '/Applications/Xcode_12.app/Contents/Developer'
  CI_XCODE_13: '/Applications/Xcode_13.0.app/Contents/Developer'
  
jobs:
  docs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gems
        id: cache-gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-v2-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-v2-
      - name: Install Bundle
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Create Jazzy Docs
        run: |
          ver=`/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" ParseCareKit/Info.plist`
          bundle exec jazzy \
            --clean \
            --author "Corey E. Baker" \
            --author_url https://www.cs.uky.edu/~baker \
            --github_url https://github.com/netreconlab/ParseCareKit \
            --root-url https://netreconlab.github.io/api/ \
            --module-version ${ver} \
            --theme apple \
            --skip-undocumented \
            --output ./docs/api \
            --build-tool-arguments -scheme,ParseCareKit,-destination,'name=iPhone 12 Pro Max' \
            --module ParseCareKit \
        env:
          DEVELOPER_DIR: ${{ env.CI_XCODE_13 }}
      - name: Deploy Jazzy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
